### ISSUE TITLE
Loading SQLiteUniversalWinJS to solution

### ISSUE THREAD

**Issue by jase88** [cloudcrypt/SQLite-Universal-WinJS-Component#3]
Hey,

Great repo - thanks for your guide! Currently having problems to add the SQLiteUniversalWinJS project to my solution:
<img src="http://i.imgur.com/3cdhGef.png"/>
Running VS2013
I already installed a vsix extension of SQLite (current version seems to be [3.11.0](https://visualstudiogallery.msdn.microsoft.com/4913e7d5-96c9-4dde-a1a1-69820d615936))

Also changed the version number on the SQLiteUniversalWinJS.vcxproj but didn't had affect - same error,

Any help is appreciated!

**Comment by cloudcrypt** [comment]
Hi! I don't have a VS2013 install handy, but I might be able to test on one later this week or early next week. Just to double check, do you have the Windows 10 Universal SDK installed on your system/in VS2013? This project is targeted for Windows 10 and the Windows Universal App Platform, (MinVersion = 10.0.10240.0), so I'm not 100% sure if you can use the Windows 10 UAP SDK in VS2013/it might need to be run in VS2015. Do you have any way of switching to VS2015?

**Comment by jase88** [comment]
Ah, yeah Win10 SDK is installed. There is a Win8.1 Shared project and a Win10 proj on that solution. You're right if it is targeted for Windows10 I might be unable to open it with VS2013. I will test the mentioned 8.1 component tomorrow (I need both). Thanks for support :)

**Comment by cloudcrypt** [comment]
I _think_ you should be able to have a solution in VS2015 that contains a Windows 10 Universal project and a Windows 8.1 Shared Universal project, since you can run and build for the 8.1SDK in VS2015 AFAIK (by choosing the that option that gives you the Windows 8.1 SDK/Utilities when customizing features in VS2015's installation).

**Comment by jase88** [comment]
Okay thanks i will try to get VS2015 the next days and report if opening works there

**Comment by jase88** [comment]
Managed to get it working with VS2015 and a new universal project :) I'm using a shared SQLite project for Win81 and a modified version of your SQLite UWP. I retargeted them all to the current SQLite version 3.11.0. Works like a charm.
