### ISSUE TITLE
SQLite component is failing on Windows App Cert Kit 10.0

### ISSUE THREAD

**Issue by jase88** [cloudcrypt/SQLite-Universal-WinJS-Component#4]
Hey,

I just realised that the App Cert Kit for Store fails on this C++ component on test of supported APIs:

> API sqlite3_bind_text in sqlite3.dll wird für diesen Anwendungstyp nicht unterstützt. SQLiteUniversalWinJS.dll ruft diese API auf.
> API sqlite3_close in sqlite3.dll wird für diesen Anwendungstyp nicht unterstützt. SQLiteUniversalWinJS.dll ruft diese API auf.
> API sqlite3_column_count in sqlite3.dll wird für diesen Anwendungstyp nicht unterstützt. SQLiteUniversalWinJS.dll ruft diese API auf.
> API sqlite3_column_name in sqlite3.dll wird für diesen Anwendungstyp nicht unterstützt. SQLiteUniversalWinJS.dll ruft diese API auf.
> API sqlite3_column_text in sqlite3.dll wird für diesen Anwendungstyp nicht unterstützt. SQLiteUniversalWinJS.dll ruft diese API auf.
> API sqlite3_exec in sqlite3.dll wird für diesen Anwendungstyp nicht unterstützt. SQLiteUniversalWinJS.dll ruft diese API auf.
> API sqlite3_finalize in sqlite3.dll wird für diesen Anwendungstyp nicht unterstützt. SQLiteUniversalWinJS.dll ruft diese API auf.
> API sqlite3_mprintf in sqlite3.dll wird für diesen Anwendungstyp nicht unterstützt. SQLiteUniversalWinJS.dll ruft diese API auf.
> API sqlite3_open_v2 in sqlite3.dll wird für diesen Anwendungstyp nicht unterstützt. SQLiteUniversalWinJS.dll ruft diese API auf.
> API sqlite3_prepare in sqlite3.dll wird für diesen Anwendungstyp nicht unterstützt. SQLiteUniversalWinJS.dll ruft diese API auf.
> API sqlite3_step in sqlite3.dll wird für diesen Anwendungstyp nicht unterstützt. SQLiteUniversalWinJS.dll ruft diese API auf.
> API sqlite3_temp_directory in sqlite3.dll wird für diesen Anwendungstyp nicht unterstützt. SQLiteUniversalWinJS.dll ruft diese API auf.

I just created a new universal app project on this github solution file and added SQLiteUniversalWinJS as reference to it.

Anyone experienced similar problems? :disappointed: Running Win8.1 with VS2015, Windows SDK 10.0.10586.0 and Windows App Cert Kit 10.0.

**Comment by cloudcrypt** [comment]
UAP Windows Universal Apps can only run on Windows 10. Could it be that you need to certify the app in WACK running on Win10?

**Comment by jase88** [comment]
I build apppackages on Win8.1 machine (not executing them there). 
WACK 10 is also used for Win81 apps (Windows Store internally uses same WACK tool for store submissions).

Started app on a Lumia Win10 device and calling _SQLite.Database.openDatabaseInFolderAsync(databaseFolder, 'dbname'),then();_ already gives me an error (not even entering promise chain)

> JavaScript runtime error: The specified module could not be found.

Not sure if this is related and might be caused by blocking this APIs.

This might be related to my configuration. I will try to run this project on a Win10 machine. After googling there are seem to be a lot failing on supported API test of WACK - also with SQLite packages etc. mostly read about uninstalling  <a href="https://support.microsoft.com/de-de/kb/2976978">KB2976978</a>. I will also try that and give feedback

**Comment by cloudcrypt** [comment]
Any news with this issue?

**Comment by jase88** [comment]
Nope sorry - had some issues with async calls with this C++ Wrapper on 8.1 when firing multiple statements.

> The application called an interface that was marshalled for a different thread.

Occured randomly on different statements. So i dropped this solution.

I'm now using a C++ Wrapper from litehelpers/Cordova-sqlite-legacy via cordova plugin.

I will close it, because I won't investigate any further
